In [19]:
#简单来说axis并不是简单的代表行和列，[[],[]] 最外面的括号代表0，依次往里的括号对应的axis的计数依次加1
#操作方式：如果指定轴进行相关操作，那么他会使用轴下的每个（直接子元素）的第0个，第1个，第2个。。。分别进行相关操作
import numpy as np
n = np.random.randint(10,size=(2,3,4))
print(n)
print(n.max(axis=0))
np.delete,是直接删除指定轴下的第几个直接子元素

[[[4 1 1 8]
  [2 2 4 7]
  [7 3 9 5]]

 [[5 7 3 6]
  [9 7 0 5]
  [8 6 4 5]]]
[[5 7 3 8]
 [9 7 4 7]
 [8 6 9 5]]
