In [2]:
# 列表的形式创建数组
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
help(np.array)  #可以查看数组中有哪些参数

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [4]:
#使用np.arange创建数组
#和python中range函数一样的
#这里的2是步长
b = np.arange(0,10,2)
print(b)

[0 2 4 6 8]


In [5]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [16]:
#使用np.random生成随机数组
c = np.random.random((2,5))
d = np.random.random()
print('d',d)
c

d 0.3743004946377546


array([[0.51973748, 0.31009643, 0.4448339 , 0.12474022, 0.49988463],
       [0.52726283, 0.44930023, 0.09943531, 0.93396421, 0.46285163]])

In [5]:
#值的范围由0，9来确定，size确定几行几列
e = np.random.randint(0,9,size=(4,4,))
e

array([[8, 6, 6, 1],
       [6, 5, 5, 4],
       [7, 6, 1, 0],
       [0, 6, 1, 5]])