In [1]:
import numpy as np

array([[5, 1, 6, 8],
       [4, 0, 7, 4],
       [1, 0, 1, 7]])

In [8]:
np.random.seed(1)
#用于指定随机数生成时所用算法开始的整数值，如果使用相同的seed（）值，则每次生成的随机数都相同，
#如果不设置这个值，则系统根据时间自己选择这个值，此时每次生成的随机数因为时间差异而不同，一般没有要求不用设置
np.random.rand()

0.417022004702574

In [9]:
np.random.rand(2,3,4)
#生成一个值为[0,1)之间的数组，形状由参数决定，如果没有参数，那么将返回一个随机值

array([[[7.20324493e-01, 1.14374817e-04, 3.02332573e-01, 1.46755891e-01],
        [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
        [5.38816734e-01, 4.19194514e-01, 6.85219500e-01, 2.04452250e-01]],

       [[8.78117436e-01, 2.73875932e-02, 6.70467510e-01, 4.17304802e-01],
        [5.58689828e-01, 1.40386939e-01, 1.98101489e-01, 8.00744569e-01],
        [9.68261576e-01, 3.13424178e-01, 6.92322616e-01, 8.76389152e-01]]])

In [10]:
np.random.randn(2,3,4)
#生成均值为0，标准差为1的标准正态分布的值

array([[[ 0.53381091, -0.0919733 ,  1.91382039,  0.33079713],
        [ 1.14194252, -1.12959516, -0.85005238,  0.96082   ],
        [-0.21741818,  0.15851488,  0.87341823, -0.11138337]],

       [[-1.03803876, -1.00947983, -1.05825656,  0.65628408],
        [-0.06249159, -1.73865429,  0.103163  , -0.62166685],
        [ 0.27571804, -1.09067489, -0.60998525,  0.30641238]]])

In [23]:
np.random.randint(10,size=(2,3,4))
#生成指定范围内的随机数，并且可以通过size参数指定维数

array([[[0, 6, 5, 1],
        [2, 1, 5, 4],
        [0, 7, 8, 9]],

       [[5, 7, 0, 9],
        [3, 9, 1, 4],
        [4, 6, 8, 8]]])

In [71]:
data = np.random.randint(10,size=(10,))
print(data)
data1 = np.random.choice(data,size = (3,2))
print(data1)
data2 = np.random.choice(data,2)
print(data2)
data3 = np.random.randint(10,30)
print(data3)
#从一个列表或数组中随机进行采样。或者是从指定的区间进行采样，采样个数可以通过参数指定,注意这个choice针对的是一维数组

[4 3 6 7 6 3 0 6 4 7]
[[0 6]
 [7 3]
 [7 7]]
[7 4]
23


In [74]:
data = np.random.randint(10,size=(10,5))
print(data)
np.random.shuffle(data) #不会返回值，直接进行更新
data
#将元素的位置进行随机更换

[[7 3 2 2 2]
 [6 6 0 1 5]
 [6 5 8 8 5]
 [5 7 5 9 1]
 [3 9 3 3 3]
 [6 1 3 0 5]
 [0 5 2 7 6]
 [4 0 2 4 8]
 [7 6 7 7 1]
 [7 7 3 8 3]]


array([[6, 5, 8, 8, 5],
       [7, 6, 7, 7, 1],
       [6, 6, 0, 1, 5],
       [3, 9, 3, 3, 3],
       [4, 0, 2, 4, 8],
       [6, 1, 3, 0, 5],
       [7, 7, 3, 8, 3],
       [5, 7, 5, 9, 1],
       [0, 5, 2, 7, 6],
       [7, 3, 2, 2, 2]])