In [1]:
import numpy as np

In [3]:
#不拷贝
#只是简单的赋值，不会进行拷贝
a = np.arange(10)
b = a #给a另取了一个名字
print(b is a)   # 返回true 说明 b和a 是同一个变量

True
[0 1 2 3 4 5 6 7 8 9]


In [6]:
#浅拷贝
a1 = np.arange(10)
c = a1.view()
print(c is a1,a1)  #返回fslse说明a1和c不是同一个变量，但所指向的存储空间一样
c[0] = 100
print(c,a1)

False [0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9] [100   1   2   3   4   5   6   7   8   9]


In [8]:
#深拷贝
a2 = np.arange(10)
d = a2.copy()
print(a is d,a,d)
d[0] = 100
print(a,d)

False [0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] [100   1   2   3   4   5   6   7   8   9]
