In [1]:
import numpy as np

In [10]:
a2 = np.arange(24).reshape((4,6))
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [9]:
a2<10   #生成一个新的数组全是false或true

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [11]:
a2[a2<10]   #把满足条件的全部提取出来

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a2[(a2<5)|(a2>10)]   #这里可以用｜或  &且  ~非 来多个条件选择，多个条件用()扩起来

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])