In [1]:
import numpy as np
#hsplit     按照水平方向进行切割，用于指定分割成几列，可以使用数字来代表分割成几个部分，也可以使用数组来代表分割的地方 

In [3]:
hs1 = np.random.randint(0,10,size=(3,4))
print(hs1)
np.hsplit(hs1,2)

[[4 6 9 8]
 [2 6 9 2]
 [4 1 8 4]]


[array([[4, 6],
        [2, 6],
        [4, 1]]),
 array([[9, 8],
        [9, 2],
        [8, 4]])]

In [4]:
np.hsplit(hs1,(1,2,3))

[array([[4],
        [2],
        [4]]),
 array([[6],
        [6],
        [1]]),
 array([[9],
        [9],
        [8]]),
 array([[8],
        [2],
        [4]])]

In [ ]:
# vsplit  垂直切割，用于指定分割成几行，可以使用数字来代表分割成几个部分，也可以使用数组来代表分割的地方 

In [5]:
vs1 = np.random.randint(0,10,size=(4,5))
print(vs1)

[[4 5 6 6 9]
 [8 2 8 0 6]
 [8 1 0 4 9]
 [3 8 9 2 2]]


In [9]:
np.vsplit(vs1,4)

[array([[4, 5, 6, 6, 9]]),
 array([[8, 2, 8, 0, 6]]),
 array([[8, 1, 0, 4, 9]]),
 array([[3, 8, 9, 2, 2]])]

In [ ]:
# split/array_split(array,indicate_or_seciont,axis) 用于指定切割方式，在切割的时候需要指定是按照行还是按照列，axis=1代表按照列，
# axis= 0代表按照行