In [2]:
import numpy as np

In [4]:
a1 = np.random.randint(0,5,size=(3,5))
print(a1)

[[4 2 4 1 3]
 [1 1 3 4 4]
 [2 2 1 4 0]]


In [5]:
a1*2  数组中每个数变为原来的两倍


array([[8, 4, 8, 2, 6],
       [2, 2, 6, 8, 8],
       [4, 4, 2, 8, 0]])

In [6]:
a2 = np.random.randint(0,5,size=(3,5))
print(a2)
print(a1+a2)   如果结果一样相加，就是每个元素的相加

[[0 4 2 4 1]
 [4 1 0 0 0]
 [1 0 4 0 0]]
[[4 6 6 5 4]
 [5 2 3 4 4]
 [3 2 5 4 0]]


In [7]:
#行数相同并且只有一列的数组是可以运算的
a3 = np.random.randint(0,5,size=(3,4))
a4 = np.random.randint(0,5,size=(3,1))
print(a3,a4)
print(a3+a4)

[[0 3 4 2]
 [0 3 3 4]
 [2 1 1 3]] [[1]
 [1]
 [1]]
[[1 4 5 3]
 [1 4 4 5]
 [3 2 2 4]]


In [9]:
a5 = np.array([1,2,3,4,5])
a6 = np.array([1])
print(a5+a6)

[2 3 4 5 6]


In [ ]:
#运算原则：
#如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相符或其中一方的轴长度为1，则认为他们是广播兼容的，广播会在缺失和长度为1的维度上进行