In [6]:
import numpy as np

In [25]:
#一维数组索引和切片
a1 = np.arange(10)
print(a1)
#进行索引操作
print(a1[4])
#进行切片操作    包前不包后
print(a1[0:2])
#步长
print(a1[1:6:2])
#使用负数作为索引
print(a1[-2])
print(a1[3:1:-1])
print(a1[[1,2]])

[0 1 2 3 4 5 6 7 8 9]
4
[0 1]
[1 3 5]
8
[3 2]
[1 2]


In [47]:
#多维数组
#也是通过中括号来索引切片，在中括号中，使用逗号来进行分割，逗号前面的是行，逗号后面的是列，如果多维数组中只有一个值，那么这个值就是行
a2 = np.random.randint(0,10,size=(4,6))
print(a2)
print(a2[0:4][2])  #获取a中的第三行
print(a2[0])  #获取a中第一行
print(a2[0][0])  #获取a中第一行第一列
print(a2[[1,2,3]]) #获取a中的2，3，4行
print(a2[3][2])  #获取a中第四行第三列
print(a2[[1,3],[2,3]])   #[1,2]是行  [2,3]是列
print(a2[:,1])  #获取a中所有行的第二列
#注意区别：
print(a2[[1,2],[4,5]])
print(a2[1:3,4:6])
#细品

[[5 6 6 5 6 2]
 [8 3 1 5 5 5]
 [6 4 1 8 6 3]
 [5 5 3 4 9 9]]
[6 4 1 8 6 3]
[5 6 6 5 6 2]
5
[[8 3 1 5 5 5]
 [6 4 1 8 6 3]
 [5 5 3 4 9 9]]
3
[1 4]
[6 3 4 5]
[5 3]
[[5 5]
 [6 3]]
