In [10]:
import numpy as np
a = np.random.randint(10,size=(3,4))
a[1,2]


7

In [2]:
#nan和inf都可以看做浮点类型的数，nan类等于0 缺失值，inf无穷大

In [11]:
a = a.astype(np.float)
a[1,2] = np.NAN
a

array([[ 7.,  3.,  7.,  4.],
       [ 7.,  6., nan,  3.],
       [ 3.,  1.,  2.,  6.]])

In [4]:
np.NAN!=np.NAN

True

In [5]:
#删除缺失值

In [6]:
a[0,2] = np.NAN
a

array([[ 5.,  3., nan,  8.],
       [ 1.,  3., nan,  9.],
       [ 3.,  3.,  8.,  8.]])

In [7]:
np.isnan(a)
a[(np.isnan(a))]    #找出NAN
a[~(np.isnan(a))]   # 删除NAN，并且a变成了一个一维数组

array([5., 3., 8., 1., 3., 9., 3., 3., 8., 8.])

In [12]:
lines = np.where(np.isnan(a))  #返回满足条件的行
#使用delete方法删除指定的行，axis=0表示删除行，axis=1表示删除列，lines表示删除的行号可以是个列表
a1 = np.delete(a,lines,axis=0) 
a1

array([[7., 3., 7., 4.]])