In [1]:
import numpy as np

In [15]:
t1 = np.random.randint(0,10,size=(2,3))
print(t1)

[[6 7 4]
 [9 0 9]]


In [16]:
t1.T     #把行转化为列

array([[6, 9],
       [7, 0],
       [4, 9]])

In [17]:
t1.dot(t1.T)   t1中行的每个元素与对应的t1.T中列的每个元素对应相乘，结果相加

array([[101,  90],
       [ 90, 162]])

In [18]:
t1.transpose()  #等价于t1.T  但是transpose()返回的是个引用，对他返回值的修改，会影响t1本身

array([[6, 9],
       [7, 0],
       [4, 9]])