In [1]:
import numpy as np

In [2]:
a3 = np.random.randint(0,10,size=(3,5))
print(a3)

[[5 4 4 6 9]
 [0 4 5 9 9]
 [1 2 5 7 5]]


In [3]:
a3[1] = 0
print(a3)

[[5 4 4 6 9]
 [0 0 0 0 0]
 [1 2 5 7 5]]


In [5]:
a3[1] = np.array([1,1,1,1,1])
print(a3)

[[5 4 4 6 9]
 [1 1 1 1 1]
 [1 2 5 7 5]]


In [7]:
#条件替换
a3[a3<2] = 10
print(a3)

[[ 5  4  4  6  9]
 [10 10 10 10 10]
 [10  2  5  7  5]]


In [8]:
#通过where函数来实现
result = np.where(a3<6)
print(result)  #输出结果第一个是行，第二个是列

(array([0, 0, 0, 2, 2, 2]), array([0, 1, 2, 1, 2, 4]))


In [9]:
result = np.where(a3<6,1,0) #这儿的1是小于6后要替换的结果，0是大于6后要替换的结果，必须同时有这两个参数
print(result) 

[[1 1 1 0 0]
 [0 0 0 0 0]
 [0 1 1 0 1]]
