In [8]:
import numpy as np

In [4]:
a = np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


In [4]:
a = np.array([1,2,3,4,5,6,],dtype=np.int8)
print(a)
print(a.dtype)

[1 2 3 4 5 6]
int8


In [11]:
f = np.array([1,2,3,4,5,6,],dtype=np.int8)
print(f.dtype)
print(f)
f1 = f.astype(np.int64)
print(f1)
print(f1.dtype)

int8
[1 2 3 4 5 6]
[1 2 3 4 5 6]
int64


#总结
1.为什么numpy中有这么多数据类型？
因为是基于c语言编写的
numpy为了考虑到处理海量数据的性能，针对不同的数据给不同的数据类型，来节省内存空间，所以有不同的数据类型
2.numpy数组中有哪些数据类型？
3.数据类型转换可以使用的函数？
ndarray.artype可以修改数组元素的数据类型